describe("coderadio", function()
  local coderadio = require("coderadio")
  local config = require("coderadio.config")
  local utils = require("coderadio.utils")
  local player = require("coderadio.player")
  local core = require("coderadio.core")

  describe("setup", function()
    it("should use default config when no options provided", function()
      coderadio.setup()
      local cfg = config.get()
      assert.equals(90, cfg.volume)
      assert.equals("normal", cfg.quality)
      assert.equals(false, cfg.keymaps.enable)
    end)

    it("should merge user config with defaults", function()
      coderadio.setup({
        volume = 50,
        quality = "low",
      })
      local cfg = config.get()
      assert.equals(50, cfg.volume)
      assert.equals("low", cfg.quality)
      -- Check that defaults are preserved
      assert.equals(true, cfg.ui.notifications.enabled)
    end)

    it("should handle nested config options", function()
      coderadio.setup({
        ui = {
          notifications = {
            enabled = false,
          },
        },
      })
      local cfg = config.get()
      assert.equals(false, cfg.ui.notifications.enabled)
      -- Check that other defaults are preserved
      assert.equals(true, cfg.ui.notifications.on_song_change)
    end)
  end)

  describe("utils", function()
    describe("format_time", function()
      it("should format seconds to mm:ss", function()
        assert.equals("0:00", utils.format_time(0))
        assert.equals("0:30", utils.format_time(30))
        assert.equals("1:00", utils.format_time(60))
        assert.equals("2:30", utils.format_time(150))
        assert.equals("10:05", utils.format_time(605))
      end)

      it("should handle negative values", function()
        assert.equals("0:00", utils.format_time(-10))
      end)

      it("should handle nil values", function()
        assert.equals("0:00", utils.format_time(nil))
      end)
    end)

    describe("truncate", function()
      it("should not truncate short strings", function()
        assert.equals("hello", utils.truncate("hello", 10))
      end)

      it("should truncate long strings with ellipsis", function()
        assert.equals("hello w...", utils.truncate("hello world", 10))
      end)

      it("should handle nil values", function()
        assert.equals("", utils.truncate(nil, 10))
      end)
    end)

    describe("format_progress_bar", function()
      it("should format progress bar with time", function()
        local result = utils.format_progress_bar(30, 120, 10)
        assert.is_not_nil(result)
        assert.is_true(result:find("0:30") ~= nil)
        assert.is_true(result:find("2:00") ~= nil)
      end)

      it("should handle zero duration", function()
        local result = utils.format_progress_bar(30, 0, 10)
        assert.equals("0:30", result)
      end)
    end)
  end)

  describe("player", function()
    describe("build_command", function()
      it("should build mpv command correctly", function()
        local cmd = player.build_command("mpv", "http://example.com/stream.mp3", 80)
        assert.equals("mpv", cmd[1])
        assert.is_true(vim.tbl_contains(cmd, "--no-video"))
        assert.is_true(vim.tbl_contains(cmd, "--volume=80"))
        assert.is_true(vim.tbl_contains(cmd, "http://example.com/stream.mp3"))
      end)

      it("should build ffplay command correctly", function()
        local cmd = player.build_command("ffplay", "http://example.com/stream.mp3", 80)
        assert.equals("ffplay", cmd[1])
        assert.is_true(vim.tbl_contains(cmd, "-nodisp"))
        assert.is_true(vim.tbl_contains(cmd, "80"))
      end)

      it("should build vlc command with converted volume", function()
        local cmd = player.build_command("vlc", "http://example.com/stream.mp3", 100)
        assert.equals("vlc", cmd[1])
        -- VLC volume should be 256 for 100%
        assert.is_true(vim.tbl_contains(cmd, "256"))
      end)
    end)

    describe("get_supported_players", function()
      it("should return list of supported players", function()
        local players = player.get_supported_players()
        assert.is_table(players)
        assert.is_true(#players > 0)
        assert.is_true(vim.tbl_contains(players, "mpv"))
        assert.is_true(vim.tbl_contains(players, "ffplay"))
        assert.is_true(vim.tbl_contains(players, "vlc"))
      end)
    end)
  end)

  describe("api", function()
    it("should export required functions", function()
      local api = require("coderadio.api")
      assert.is_function(api.get_now_playing)
      assert.is_function(api.start_sse_listener)
      assert.is_function(api.stop_sse_listener)
      assert.is_function(api.is_sse_active)
    end)
  end)

  describe("public api", function()
    it("should export all public functions", function()
      assert.is_function(coderadio.setup)
      assert.is_function(coderadio.play)
      assert.is_function(coderadio.pause)
      assert.is_function(coderadio.toggle)
      assert.is_function(coderadio.stop)
      assert.is_function(coderadio.volume_up)
      assert.is_function(coderadio.volume_down)
      assert.is_function(coderadio.set_volume)
      assert.is_function(coderadio.show_info)
      assert.is_function(coderadio.hide_info)
      assert.is_function(coderadio.is_playing)
      assert.is_function(coderadio.get_current_song)
      assert.is_function(coderadio.get_volume)
      assert.is_function(coderadio.statusline)
    end)

    it("should return correct initial state", function()
      coderadio.setup()
      assert.is_false(coderadio.is_playing())
      assert.is_nil(coderadio.get_current_song())
    end)

    it("should return empty statusline when not playing", function()
      coderadio.setup()
      assert.equals("", coderadio.statusline())
    end)
  end)
end)
